# Site settings
name: Yousef Raffa's Blog
title: A Hejazi in Saudi
description: "A national Saudi entrepreneur living in Jeddah (Currently in Madina). I talk about entrepreneurship in Saudi, Mac, web, photography, geocaching, and amateur radio (HZ1YR)"
baseurl: "http://yraffah.com"
url: "http://yraffah.com"
highlighter: pygments
timezone: AST
lsi: false
paginate: 10

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  # input: GFM
  
permalinks: pretty
excerpt_separator: "\n\n"

# Username for Github and Twitter
username: yraffah

# relative_permalinks: false
