# Site settings
name: Yousef Raffa's Blog
title: My personal world
email: yraffah@gmail.com
description: "Mac, Web, Photography, Geocaching, and Amateur Radio"
baseurl: ""
url: "http://yraffah.com"

# Build settings
markdown: kramdown
permalinks: pretty
timezone: AST
lsi: TRUE

