# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

# Handling Reading
safe:         false
include:      []
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Site settings
name: Yousef Raffa's Blog
title: A Hejazi in Saudi
tagline: "A Hejazi in Saudi"
description: "I write about entrepreneurship, Mac, web, photography, geocaching, and amateur radio (HZ1YR) in Saudi"
copyrights: "&copy; 2015 Yousef Raffa. All rights reserved."
baseurl: ""
url: "http://yraffah.com"
include: ['.htaccess']
highlighter: pygments
timezone: AST
lsi: false
paginate: 5
detach: false

author:
  name: "Yousef Raffa"
  email: "YRaffah@gmail.com"
  url: https://twitter.com/yraffah
  
gems:
  - jekyll-redirect-from
  
# Custom vars
version: 2.5.0

# Username for Github and Twitter
username: yraffah
github:
  repo: http://github.com/yraffah/yraffah.github.io

# Build settings
markdown: kramdown

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  input: GFM
  
permalinks: pretty
excerpt_separator: <!--break-->
