# Site settings
name: Yousef Raffa's Blog
title: A Hejazi in Saudi
tagline: "A Hejazi in Saudi"
description: "A national Saudi entrepreneur living in Madina, Saudi Arabia. I write about entrepreneurship in Saudi, Mac, web, photography, geocaching, and amateur radio (HZ1YR)"
copyrights: "&copy; 2014 Yousef Raffa. All rights reserved."
baseurl: ""
url: "http://yraffah.com"
include:     ['.htaccess']
highlighter: pygments
timezone: AST
lsi: false
paginate: 5

author:
  name: "Yousef Raffa"
  email: "YRaffah@gmail.com"
  url: https://twitter.com/yraffah
  
gems:
  - jekyll-redirect-from
  
# Custom vars
version:          2.0.0

# Username for Github and Twitter
username: yraffah
github:
  repo: http://github.com/yraffah/yraffah.github.io

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  input: GFM
  
permalinks: pretty
excerpt_separator: <!--break-->

