# Site settings
name: Yousef Raffa's Blog
title: A Hejazi in Saudi
#email: yraffah@gmail.com
description: "A national Saudi entrepreneur living in Jeddah (Currently in Madina). I talk about Mac, web, photography, geocaching, and amateur radio (HZ1YR)"
baseurl: "http://yraffah.com"
url: "http://yraffah.com"

# Build settings
markdown: kramdown
permalinks: pretty
timezone: AST
lsi: TRUE
paginate: 10
relative_permalinks: false